version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: indexer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  apollo-server:
    build:
      dockerfile: apollo_server/Dockerfile
      context: .
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_started
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/indexer

volumes:
  postgres:
